# Usar la última versión de Ubuntu como base
FROM ubuntu:latest

# Actualizar los paquetes del sistema
RUN apt-get update

# Mejorar los paquetes instalados
RUN apt-get upgrade -y

# Comando que se ejecutará al iniciar el contenedor
CMD echo "Hello, World!"
